#! /usr/bin/env php
<?php
// This script is used to repair all text attachments that weren't in Linux format.

require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT_DIR."common/attachment.php");
require_once(IA_ROOT_DIR."common/db/attachment.php");

ini_set("memory_limit", "128M");

db_connect();
$query = "SELECT * FROM ia_file;";
$attachments = db_fetch_all($query);
$fixed = 0;

log_print("Exista ".count($attachments)." atasamente...");
foreach ($attachments as $attach) {
    if (!is_textfile($attach['mime_type'])) {
        continue;
    }
    log_print('Repar '.$attach['page'].'\\'.$attach['name']);
    dos_to_unix(attachment_get_filepath($attach));
    $fixed++;
}
log_print("S-au reparat ".$fixed." atasamente!");
