#! /usr/bin/env php
<?php

// Adds a `remote_ip_info` field to the following database tables:
// file, job, ia_textblock, ia_textblock_revision

require_once(dirname($argv[0]) . "/utilities.php");

function has_remote_ip_info($table) {
    $cols = db_fetch_all("DESCRIBE `{$table}`");
    log_assert($cols);
    foreach ($cols as $column) {
        if ('remote_ip_info' == strtolower($column['Field'])) {
            return true;
        }
    }
    return false;
}

function add_remote_ip_info($table) {
    db_query("ALTER TABLE `{$table}` ADD `remote_ip_info` VARCHAR( 128 ) NULL
            COMMENT 'IP address of the user who created this entry.'");
    db_query("ALTER TABLE `{$table}` ADD INDEX ( `remote_ip_info` )");
}

db_connect();
$tables = array('ia_file', 'ia_job', 'ia_textblock',
        'ia_textblock_revision');
foreach ($tables as $table) {
    if (!has_remote_ip_info($table)) {
        log_print("Adding remote_ip_info for table {$table}");
        add_remote_ip_info($table);
    } else {
        log_print("Skipping {$table}");
    }
}
log_print("Done");

?>
