#! /usr/bin/env php
<?php
require_once(dirname($argv[0]) . '/utilities.php');
require_once(IA_ROOT_DIR . 'common/db/db.php');
require_once(IA_ROOT_DIR . 'common/db/db_mysql.php');
db_connect();

$result = db_fetch('DESCRIBE `ia_round` `type`');
if (getattr($result, 'Type') == "enum('classic','archive','user-defined')") {
    db_query("ALTER TABLE `ia_round` modify `type` enum('classic','archive',"
            . "'user-defined','penalty-round') DEFAULT NULL");
}

$result = db_fetch('DESCRIBE `ia_job` `submissions`');
if (getattr($result, 'Type') == null) {
    db_query('ALTER TABLE `ia_job` add column `submissions` int'
            . '(11) DEFAULT 0');
}

$result = db_fetch('DESCRIBE `ia_score_user_round_task` `submits`');
if (getattr($result, 'Type') == null) {
    db_query('ALTER TABLE `ia_score_user_round_task` add column `submits` int'
            . '(11) DEFAULT 1');
}

?>
