#! /usr/bin/env php

<?php

// This scripts adds a new column in ia_task and new tabel for task ratings

require_once(dirname($argv[0]) . "/utilities.php");

db_connect();

$query = "ALTER TABLE ia_task ADD COLUMN rating float";
db_query($query);

$query = "CREATE TABLE ia_task_ratings (
    task_id VARCHAR(64) NOT NULL,
    user_id int NOT NULL,
    idea int NOT NULL,
    theory int NOT NULL,
    coding int NOT NULL,
    PRIMARY KEY(task_id, user_id))";

db_query($query);

?>
