#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");

db_connect();

$s = db_fetch_all("SELECT T.id, T.title, T.page_name, U.forum_topic FROM ia_task T,
    ia_textblock U WHERE T.page_name = U.name AND T.id IN 
    (SELECT task_id FROM ia_round_task WHERE round_id = 'arhiva')");

foreach($s as $problem) {
    $topic = $problem['forum_topic'];
    $page_name = $problem['page_name'];
    $title = $problem['title'];
    $s1 = db_fetch("SELECT ID_MSG FROM ia_smf_messages WHERE ID_TOPIC = '$topic'");
    $message = $s1['ID_MSG'];
    $new_text = 'Aici puteti discuta despre problema [url=http://infoarena.ro/' . $page_name . ']' . $title . '[/url].';
    $new_text = mysql_real_escape_string($new_text);
    db_query("UPDATE ia_smf_messages SET body = '$new_text' WHERE ID_MSG = '$message'");
}

?>

