#! /usr/bin/env php
<?php

// This script migrates cedilla diacritics to comma-below in all textblocks
// and their revisions.

require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT_DIR . "common/common.php");

db_connect();

function change_special_chars($table) {
    $res = db_query("SELECT * FROM $table");

    while ($row = db_next_row($res)) {
        $new_text = text_cedilla_to_comma_below_st($row["text"]);

        if ($row["text"] != $new_text) {
            db_query(sprintf("UPDATE `%s` SET text = %s WHERE name = %s AND
                timestamp = %s", db_escape($table), db_quote($new_text),
                db_quote($row["name"]), db_quote($row["timestamp"])));

            log_print(sprintf("Changed special characters from textblock %s".
                        "from %s", $row["name"], $row["timestamp"]));
        }
    }
}

change_special_chars("ia_textblock");
change_special_chars("ia_textblock_revision");

?>
