#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");

// This is a really dumb script that calls to mysqldump.
// Uses auth stuff from config.php.
// FIXME: password visible in ps list. How retarded.

if (isset($argv[1])) {
    $backup_file = $argv[1];
} else {
    $backup_file = IA_ROOT_DIR . "backup.sql.gz";
}

$cmd = sprintf("mysqldump --user=%s --password=%s --host=%s %s"
        ." | gzip > %s",
        IA_DB_USER, IA_DB_PASS, IA_DB_HOST, IA_DB_NAME, $backup_file);

log_print("Running '$cmd'");
system($cmd);

?>
