#! /usr/bin/env php
<?php
require_once(dirname($argv[0]) . "/utilities.php");

db_connect();
$query = "ALTER TABLE `webdb`.`ia_job`
    DROP INDEX `by_round`,
    ADD INDEX by_round USING BTREE(`round_id`, `id`),
    DROP INDEX `by_task`,
    ADD INDEX by_task USING BTREE(`task_id`, `id`),
    DROP INDEX `by_round_task`,
    ADD INDEX by_round_task USING BTREE(`round_id`, `task_id`, `id`),
    DROP INDEX `by_user`,
    ADD INDEX by_user USING BTREE(`user_id`, `id`),
    DROP INDEX `submit_time`";

db_query($query);

?>
