#! /usr/bin/env php
<?php
require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT_DIR . "common/db/blog.php");
require_once(IA_ROOT_DIR."common/textblock.php");

ini_set("memory_limit", "128M");

db_connect();

$query = "DROP TABLE IF EXISTS `ia_blog_forum`";
db_query($query);
$query = "CREATE TABLE `ia_blog_forum` (
   `textblock` VARCHAR(64) NOT NULL,
   `topic_id` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE latin1_general_ci;";
db_query($query);


$blog_posts = blog_get_range('', 0, 666013);
$pattern = '/==\ *BlogCommentCount\(\ *topic_id="\ *([0-9]*).*0*\ *"\ *\)\ *==/i';
foreach ($blog_posts as $post) {
    $content = $post['text'];
    if (preg_match($pattern, $content, $matches)) {
        $topic_id = $matches[1];
        log_print($post['name'].' -> '.$topic_id);
        $query = sprintf("INSERT INTO ia_blog_forum VALUES('%s', %s)", db_escape($post['name']), db_escape($topic_id));
        db_query($query);

        $content = preg_replace($pattern, "", $content);

        // Build new page
        $new_page['name'] = $post['name'];
        $new_page['text'] = $content;
        $new_page['title'] = $post['title'];
        $new_page['security'] = $post['security'];
        $new_page['creation_timestamp'] = $post['creation_timestamp'];
        $new_page['timestamp'] = null;
        $new_page['user_id'] = 1; // update as "domino" :)
        $new_page['remote_ip_info'] = getattr($post, 'remote_ip_info');

        // It worked
        if (!textblock_validate($new_page)) {
            textblock_add_revision($new_page['name'], $new_page['title'],
                                   $new_page['text'], $new_page['user_id'],
                                   $new_page['security'], $new_page['timestamp'],
                                   $new_page['creation_timestamp'],
                                   $new_page['remote_ip_info']);
        } else {
            log_error('Eroare la validarea textblock-ului!');
            return false;
        }
    }
    else {
        log_warn('Nu s-a găsit topic pentru "'.$post['title'].'"!');
    }
}

?>
