#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . '/utilities.php');
require_once(Config::ROOT . 'common/db/db.php');
require_once(Config::ROOT . 'www/controllers/attachment.php');
require_once(Config::ROOT . 'www/controllers/image_attachment.php');
require_once(Config::ROOT . 'common/db/attachment.php');
require_once(Config::ROOT . 'common/cache.php');
require_once(Config::ROOT . 'common/db/user.php');
require_once(Config::ROOT . 'common/avatar.php');
require_once(Config::ROOT . 'common/db/textblock.php');

// Database connect
db_connect();
$verbose = in_array('-v', $argv);
$is_setup = in_array('setup', $argv);

// Managing the userinfo template from the textblock table
if (read_bool('Do you want to change the template/userinfo textblock?',
        $is_setup)) {
    $textfortextblock = "table(compact). |=/5. ==UserImage".
    "(user=\"%user%\" size=\"big\")==\r\n{'Vezi soluțiile trimise':monitor?use".
    "r=%user%}\r\n|_. Nume | == userinfo(user=\"%user%\" info=\"fullname\")== ".
    "|\r\n| |_. Cont | ==userinfo(user=\"%user%\" info=\"username\")== |\r\n| ".
    "|_. Rating | ==userinfo(user=\"%user%\" info=\"rating\")== |\r\n| |_. Sta".
    "tut | ==userinfo(user=\"%user%\" info=\"security\")== |\r\n\r\n\r\n";
    textblock_add_revision('template/userinfo', 'template/userinfo',
            $textfortextblock, 1, 'protected');
}

// getting the user list
$userlist = user_get_list(false);

// taking care of the noimage file
$noimage_filepath = attachment_get_filepath(attachment_get('noimage',
                    'template/infoarena'));
// creating the avatar folder if it does not exists, and grant it permissions
if (file_exists(IA_AVATAR_FOLDER) == false) {
    mkdir(IA_AVATAR_FOLDER, 0777);
}
$size_types = array('tiny', 'small', 'normal', 'big', 'full');
foreach ($size_types as $size) {
    if (file_exists(IA_AVATAR_FOLDER . '/' . $size) == false) {
        mkdir(IA_AVATAR_FOLDER . '/' . $size, 0777);
    }
}

// resizing the noimage file
$img_info = getimagesize($noimage_filepath);
avatar_cache_resized($noimage_filepath, $img_info, 'noimage');

// Going through all the users
foreach ($userlist as $user) {
    if (!is_user_name($user)) {
        log_warn('Invalid username: ' . $user);
        continue;
    }
    $attach = attachment_get('avatar', 'utilizator/' . $user);
    $found = !is_null($attach);

    if ($found) {
        $real_name = attachment_get_filepath($attach);
        $found = file_exists($real_name);
        if (!$found) {
            log_warn('File does not exists but it is in the Database.');
        }
    }

    if (!$found) {
        continue;
    }

    $img_info = getimagesize($real_name);
    if ($img_info == false) {
        continue;
    }

    // The user has a valid image, resizing it, but keeping the attachment
    if ($verbose) {
        log_print('Processing user: ' . $user);
    }
    avatar_cache_resized($real_name, $img_info, "a".$user);
}

?>
