#! /usr/bin/env php
<?php
require_once(dirname($argv[0]) . '/utilities.php');
require_once(IA_ROOT_DIR . 'common/db/db.php');
require_once(IA_ROOT_DIR . 'common/db/db_mysql.php');
require_once(IA_ROOT_DIR . 'common/db/task.php');

db_connect();

$result = db_fetch('DESCRIBE `ia_task` `security`');
if (getattr($result, 'Type') == null) {
    // We use direct aproach because the validation form task_get_all would fail
    $tasks = db_fetch_all("SELECT * FROM `ia_task`");
    db_query("ALTER TABLE `ia_task` CHANGE `hidden` `security` enum('private'"
           . ", 'protected', 'public') DEFAULT 'private'");

    // We correct the security type (hidden -> private, not hidden -> public)
    foreach ($tasks as $task) {
        $new_security = ($task['hidden'] == 0) ? 'public' : 'private';
        db_query(sprintf("UPDATE `ia_task` SET `security` = '%s' WHERE "
                       . " `ia_task`.`id` = '%s'", db_escape($new_security),
                        db_escape($task['id'])));
    }

    db_query("CREATE INDEX `by_security` ON `ia_task` (`security`)");
}
