#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");

db_connect();

$result = db_fetch('DESCRIBE `ia_task` `test_count`');
if ($result !== null) {
	exit(0);
}
db_query("
ALTER TABLE `ia_task`
    ADD COLUMN `test_count` INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN `test_groups` VARCHAR(256),
    ADD COLUMN `public_tests` VARCHAR(256),
    ADD COLUMN `evaluator` VARCHAR(64),
    ADD COLUMN `use_ok_files` TINYINT(1) NOT NULL DEFAULT 1");

$query = "SELECT * FROM `ia_parameter_value`
          WHERE `object_type` = 'task' AND
                `parameter_id` != 'memlimit' AND
                `parameter_id` != 'timelimit'";
$rows = db_fetch_all($query);

$tasks = array();

foreach ($rows as $row) {
    $task_id = $row["object_id"];
    if (!array_key_exists($task_id, $tasks)) {
        $tasks[$task_id] = array();
    }

    $tasks[$task_id][$row["parameter_id"]] = $row["value"];
}

foreach ($tasks as $task_id => $task) {
    $params = array();

    if (!isset($task["tests"])) {
        log_error("Task $task_id doesn't have a test number");
    } else {
        $params["test_count"] = $task["tests"];
    }
    if (!isset($task["okfiles"])) {
        log_error("Task $task_id doesn't have a okfiles bool");
    } else {
        $params["use_ok_files"] = $task["okfiles"];
    }

    $params["test_groups"] = getattr($task, "testgroups", "");
    $params["evaluator"] = getattr($task, "evaluator", "");

    log_print("Migrating parameters for task $task_id");
    db_update('ia_task', $params, '`id` = ' . db_quote($task_id));
}

db_query("DELETE FROM `ia_parameter_value`
          WHERE `object_type` = 'task' AND
                `parameter_id` != 'timelimit' AND
                `parameter_id` != 'memlimit'");

?>

