#!/usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT_DIR . 'common/db/db.php');

db_connect();

$result = db_fetch('DESCRIBE `ia_file` `aws`');

if ($result === null) {
    db_query("ALTER TABLE `ia_file` ADD `aws` BOOL DEFAULT false");
    echo "Migration complete\n";
} else {
    echo "Migration already executed\n";
}

