#! /usr/bin/env php
<?php

require_once dirname($argv[0]) . "/utilities.php";
require_once IA_ROOT_DIR . "common/db/db_mysql.php";
require_once IA_ROOT_DIR . "common/db/db.php";

ini_set('memory_limit', '512M');

db_connect();

$result = db_fetch('DESCRIBE `ia_score_user_round_task` `incorrect_submits`');
if ($result === null) {
    db_query("
        ALTER TABLE `ia_score_user_round_task`
        ADD COLUMN `incorrect_submits` int(11) DEFAULT 0 NOT NULL
    ");
    log_print('Successfully added the column `incorrect_submits` to `ia_score_user_round_task`');
}

db_query("
    ALTER TABLE `ia_score_user_round_task`
    MODIFY COLUMN `submits` int(11) DEFAULT 0 NOT NULL
");
log_print('Successfully altered the column `submits` from `ia_score_user_round_task`');

$start_time = time();

$query = "SELECT user_id, round_id, task_id, score
          FROM ia_job
          ORDER BY user_id, round_id, task_id";

$result = mysql_query($query);
$num_rows = mysql_num_rows($result);

log_print("Total rows to process: $num_rows");

$row_count = 0;
$prev_user_id = -1;
$prev_round_id = -1;
$prev_task_id = -1;
$submit_count = 0;
$incorrect_submit_count = 0;
while ($row = mysql_fetch_assoc($result)) {
    $user_id = $row['user_id'];
    $round_id = $row['round_id'];
    $task_id = $row['task_id'];
    $score = $row['score'];

    if ($user_id !== $prev_user_id ||
        $round_id !== $prev_round_id ||
        $task_id !== $prev_task_id) {
        if ($prev_user_id !== -1) {
            db_update("ia_score_user_round_task",
                      array(
                          'submits' => $submit_count,
                          'incorrect_submits' => $incorrect_submit_count,
                      ),
                      "user_id=$prev_user_id AND round_id='$prev_round_id' AND task_id='$prev_task_id'");
        }
        $submit_count = 0;
        $incorrect_submit_count = 0;
    }

    $submit_count++;
    if ($score < 100) {
        $incorrect_submit_count++;
    }

    $prev_user_id = $user_id;
    $prev_round_id = $round_id;
    $prev_task_id = $task_id;

    $row_count++;
    if ($row_count % 100000 === 0) {
        log_print("Currently at row $row_count");
    }
}

db_update("ia_score_user_round_task",
          array(
              'submits' => $submit_count,
              'incorrect_submits' => $incorrect_submit_count,
          ),
          "user_id=$prev_user_id AND round_id='$prev_round_id' AND task_id='$prev_task_id'");

mysql_free_result($result);

$end_time = time();
log_print('Time: '.($end_time - $start_time).'s');

log_print('Successfully updated the count columns in table `ia_score_user_round_task`');
