#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . '/utilities.php');
require_once(IA_ROOT_DIR . 'common/db/db.php');

db_connect();

$query = "CREATE TABLE IF NOT EXISTS ia_tokens (`identifier` VARCHAR(64) "
       . "NOT NULL, `tokens` INT NOT NULL, `timestamp` DATETIME, PRIMARY KEY "
       . "(identifier))";
db_query($query);
?>
