#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");

$home_dir = exec('echo $HOME');
define("IA_BACKUP_REPO_DIR", "$home_dir/backup/infoarena");
define("IA_BACKUP_SSL_CERT", "$home_dir/.ssh/ia-backup");

function check_env() {
    log_assert(is_dir(IA_BACKUP_REPO_DIR));
    log_assert(file_exists(IA_BACKUP_SSL_CERT));
    log_assert(exec('which rsync'), "Please install rsync");
}

function exec_rsync($source_dir, $target_dir) {
    log_print("rsync $source_dir -> $target_dir");
    $cmd = sprintf("rsync -avC --delete --rsh='ssh -p 21883 -i %s' "
            ."backup@infoarena.ro:%s %s/%s", IA_BACKUP_SSL_CERT, $source_dir,
            IA_BACKUP_REPO_DIR, $target_dir);
    system($cmd);
}

/*
// Not needed anymore because cp -alr seems to work fine.
function archive_attachments() {
    log_print("Archiving attachments");
    $archive_file = sprintf("%s/archive/attach/attach-%s.tar.gz",
            IA_BACKUP_REPO_DIR, backup_timestamp());
    system(sprintf("tar czf %s %s/attach-live/ar*", $archive_file,
            IA_BACKUP_REPO_DIR));
}
*/

function sync_attachments() {
    $last_snapshot = exec(sprintf("ls -tr1 '%s'",
            IA_BACKUP_REPO_DIR."/attach"));
    $new_snapshot = backup_timestamp();
    log_print("Duplicating last snapshot with hard links "
            ."($last_snapshot -> $new_snapshot)");
    system(sprintf("cp -alr %s %s",
            IA_BACKUP_REPO_DIR."/attach/".$last_snapshot,
            IA_BACKUP_REPO_DIR."/attach/".$new_snapshot));
    log_print("Syncing last snapshot");
    exec_rsync('attach-live/', "attach/$new_snapshot/");
}

function main() {
    global $argv;
    check_env();
    exec_rsync('ia-backup/', 'archive/');
    sync_attachments();
}

main();

?>
