#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");

$home_dir = exec('echo $HOME');
define("IA_BACKUP_REPO_DIR", "$home_dir/backup/infoarena");
define("IA_BACKUP_SSL_CERT", "$home_dir/.ssh/ia-backup");

function week_timestamp() {
    return date("YW");
}

function check_env() {
    log_assert(is_dir(IA_BACKUP_REPO_DIR));
    log_assert(file_exists(IA_BACKUP_SSL_CERT));
    log_assert(exec('which rsync'), "Please install rsync");
}

function exec_rsync($source_dir, $target_dir, $delete_extraneous=false) {
    log_print("rsync $source_dir -> $target_dir");
    $delete_arg = $delete_extraneous ? '--delete' : '';
    $cmd = sprintf("rsync -avC {$delete_arg} --rsh='ssh -p 21883 -i %s' "
            ."backup@infoarena.ro:%s %s/%s", IA_BACKUP_SSL_CERT, $source_dir,
            IA_BACKUP_REPO_DIR, $target_dir);
    system($cmd);
}

function sync_attachments() {
    $new_snapshot = week_timestamp();
    if (!is_dir(IA_BACKUP_REPO_DIR."/attach")) {
        mkdir(IA_BACKUP_REPO_DIR."/attach");
    }
    $last_snapshot = exec(sprintf("ls -1 '%s'",
            IA_BACKUP_REPO_DIR."/attach"));
    if ($last_snapshot && $last_snapshot != $new_snapshot) {
        log_print("Duplicating last snapshot with hard links "
                ."($last_snapshot -> $new_snapshot)");
        system(sprintf("cp -alr %s %s",
                IA_BACKUP_REPO_DIR."/attach/".$last_snapshot,
                IA_BACKUP_REPO_DIR."/attach/".$new_snapshot));
    }
    log_print("Syncing last snapshot");
    exec_rsync('attach-live/', "attach/$new_snapshot/", true);
}

function main() {
    global $argv;
    check_env();
    exec_rsync('ia-backup/', 'archive/');
    sync_attachments();
}

main();

?>
