#! /usr/bin/env php
<?php
/*
   This registers users from infoarena 1.0 contests.
   This should have been done in the import script.
*/

require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT_DIR."www/config.php");
require_once(IA_ROOT_DIR."common/db/db.php");

define("IA1_TIMESTAMP", 1165000000);

db_connect();
$query = "INSERT IGNORE INTO ia_user_round (user_id, round_id)
          SELECT DISTINCT user_id, round_id FROM ia_score
          WHERE name='score' AND round_id <> 'arhiva'
            AND ".IA1_TIMESTAMP." > (SELECT value from ia_parameter_value
                                     WHERE object_type = 'round'
                                     AND object_id = ia_score.round_id
                                     AND parameter_id = 'rating_timestamp')";
db_query($query);
?>
