#! /usr/bin/env php
<?php
require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT_DIR . "common/textblock.php");

db_connect();
db_query("ALTER TABLE `ia_textblock` ADD COLUMN `forum_topic` INT UNSIGNED DEFAULT NULL");
db_query("ALTER TABLE `ia_textblock_revision` ADD COLUMN `forum_topic` INT UNSIGNED DEFAULT NULL");

$blog_pages = db_fetch_all("SELECT * FROM `ia_blog_forum`");

foreach ($blog_pages as $blog_page) {
    $page = textblock_get_revision($blog_page["textblock"]);

    $page["forum_topic"] = $blog_page["topic_id"];
    $page["user_id"] = 1490;               // update as "bogdan2412" :)
    $page["timestamp"] = null;

    if (count(textblock_validate($page)) == 0) {
        textblock_add_revision($page['name'], $page['title'], $page['text'],
                               $page['user_id'], $page['security'],
                               $page["forum_topic"], $page['timestamp'],
                               $page['creation_timestamp'],
                               getattr($page, 'remote_ip_info'));
    } else {
        log_error('Eroare la procesarea ia_blog_forum!');
    }
}

db_query("DROP TABLE `ia_blog_forum`");


$task_pages = db_fetch_all("SELECT `page_name` FROM `ia_task`");

foreach ($task_pages as $task_page) {
    $page = textblock_get_revision($task_page["page_name"]);

    $pattern = '/==\ *smftopic\(\ *topic_id="\ *([0-9]*).*0*\ *"\ *\)\ *==/i';
    if (preg_match($pattern, $page['text'], $matches)) {
        $topic_id = $matches[1];

        $page["text"] = preg_replace($pattern, "", $page["text"]);
        $page["forum_topic"] = $topic_id;
        $page["user_id"] = 1490;               // update as "bogdan2412" :)
        $page["timestamp"] = null;

        if (count(textblock_validate($page)) == 0) {
            textblock_add_revision($page['name'], $page['title'], $page['text'],
                                   $page['user_id'], $page['security'],
                                   $page["forum_topic"], $page['timestamp'],
                                   $page['creation_timestamp'],
                                   getattr($page, 'remote_ip_info'));
        } else {
            log_error('Eroare la procesarea paginii ' . $page["name"] . '!');
        }
    } else {
        if (stristr($page["text"], 'SmfTopic')) {
            log_warn('Eroare de regexp pentru "'.$task['id'].'"!');
        }
        log_warn($page["name"] . " nu are nici un topic asociat");
    }
}

?>

