#!/usr/bin/env php
<?php

use Aws\S3\S3Client;
use Guzzle\Batch\BatchBuilder;

require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT_DIR . "common/db/db.php");
require_once(IA_ROOT_DIR . "common/attachment.php");

db_connect();

$attachments = db_fetch_all('SELECT * FROM ia_file');

$count = 0;
$ignored = 0;

$s3 = S3Client::factory(array(
    'key' => AWS_RW_ACCESS_KEY,
    'secret' => AWS_RW_SECRET_KEY,
));

$batch = BatchBuilder::factory()
    ->transferCommands(25)
    ->autoFlushAt(25)
    ->notify(function (array $transferredItems) {
        foreach ($transferredItems as $item) {
            echo ".";
        }
    })
    ->build();

echo "Starting requests";
foreach ($attachments as $attachment) {
    if (attachment_should_be_in_aws($attachment['page'], $attachment['name'])) {
        if ($attachment['aws']) {
            $ignored++;
            continue;
        }

        $batch->add(attachment_put_in_aws_command(
                $s3,
                'ia-grader-files',
                attachment_get_aws_name($attachment),
                attachment_get_filepath($attachment)
            ));

       ++$count;
    }
}

$batch->flush();
echo "\n";

foreach ($attachments as $attachment) {
    if (attachment_should_be_in_aws($attachment['page'], $attachment['name'])) {
        if ($attachment['aws']) {
            continue;
        }
        attachment_update(
            $attachment['id'], $attachment['name'],
            $attachment['size'], $attachment['mime_type'],
            $attachment['page'], $attachment['user_id'],
            $attachment['remote_ip_info'], true);
    }
}

log_print("Done moving $count files to s3, $ignored files ignored, now starting deletion");
foreach ($attachments as $attachment) {
    if (attachment_should_be_in_aws($attachment['page'], $attachment['name'])) {
        @unlink(attachment_get_filepath($attachment));
    }
}

log_print("Done deleting");
