#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");

// This is a really dumb script that calls to mysqldump.
// Uses auth stuff from config.php.
// FIXME: password visible in ps list. How retarded.

$cmd = sprintf("mysqldump --user=%s --password=%s --host=%s %s > %s",
        IA_DB_USER, IA_DB_PASS, IA_DB_HOST, IA_DB_NAME, IA_ROOT_DIR . "backup.sql");
log_print("Running '$cmd'");
system($cmd);

?>
