#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");

// This is a really dumb script that calls to mysqldump.
// Uses auth stuff from config.php.
// FIXME: password visible in ps list. How retarded.

$cmdline = "mysql";
$cmdline .= " --user=".DB_USER;
$cmdline .= " --password=".DB_PASS;
if (strstr(DB_HOST, ":")) {
    list($host, $port) = explode(':', DB_HOST);
    $cmdline .= " --host=".$host;
    $cmdline .= " --port=".$port;
} else {
    $cmdline .= " --host=".DB_HOST;
}
$cmdline .= " ".DB_NAME;

magic_exec($cmdline);

?>
