#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");

// This is a really dumb script that calls to mysqldump.
// Uses auth stuff from config.php.
// FIXME: password visible in ps list. How retarded.

$cmdline = "mysql";
$cmdline .= " --user=".IA_DB_USER;
$cmdline .= " --password=".IA_DB_PASS;
if (strstr(IA_DB_HOST, ":")) {
    list($host, $port) = explode(':', IA_DB_HOST);
    $cmdline .= " --host=".$host;
    $cmdline .= " --port=".$port;
} else {
    $cmdline .= " --host=".IA_DB_HOST;
}
$cmdline .= " ".IA_DB_NAME;

magic_exec($cmdline);

?>
