#! /usr/bin/env php
<?php

// Run this script when you change the database schema and want it saved
// in repository.
//
// It will safely strip the database off sensitive/un-important data for
// development.

// name of temporary database where we transfer the tables and trim them down
// configured sql user must have full privileges on this database.
define("IA_DB_TEMP_NAME", "infoarena_temp");

require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT."common/db/db.php");

$tempdb = IA_DB_TEMP_NAME;
$smfprefix = DB_SMF_PREFIX;

log_print("NOTE: This script requires that the MySQL user has ALL PRIVILEGES "
          ."to temporary database {$tempdb}.");
log_print("WARNING: This will empty database {$tempdb} and also rewrite file "
          .IA_ROOT."db.sql");
if (!read_bool("Should I continue?")) {
    log_error("Aborted by user");
}

// get table list
$tables = db_fetch_all("SHOW TABLES");
//  - flatten array
$tables = array_map('array_values', $tables);
$tables = array_map('array_pop', $tables);
$tables = array_values($tables);

// duplicate each table
log_print("Duplicating database ...");
foreach ($tables as $table) {
    log_print($table);

    // drop
    $query = "DROP TABLE IF EXISTS `{$tempdb}`.`{$table}`";
    db_query($query);
    // copy
    $query = "CREATE TABLE `{$tempdb}`.`{$table}`\n"
             ."SELECT * FROM `{$table}`";
    db_query($query);
}

// censoring sensitive data
//  - passwords
db_query("UPDATE `{$tempdb}`.ia_user
          SET `password` = SHA1(CONCAT(LCASE(username), LCASE(username)))");
db_query("UPDATE `{$tempdb}`.{$smfprefix}members
          SET `passwd` = SHA1(CONCAT(LCASE(memberName), LCASE(memberName)))");
//  - email
db_query("UPDATE `{$tempdb}`.ia_user
          SET email = CONCAT(username, '@example.com')");
db_query("UPDATE `{$tempdb}`.{$smfprefix}members
          SET emailAddress = CONCAT(memberName, '@example.com')");
//  - attachments
db_query("DELETE FROM `{$tempdb}`.ia_file
          WHERE name <> 'noimage'");
// - personal and public messages on forum (we have some private threads)
db_query("DELETE FROM `{$tempdb}`.`{$smfprefix}messages`");
db_query("DELETE FROM `{$tempdb}`.`{$smfprefix}personal_messages`");
db_query("DELETE FROM `{$tempdb}`.`{$smfprefix}polls`");
db_query("DELETE FROM `{$tempdb}`.`{$smfprefix}poll_choices`");
db_query("DELETE FROM `{$tempdb}`.`{$smfprefix}sessions`");

// now dump it all in versioned file

// This is a really dumb script that calls to mysqldump.
// Uses auth stuff from config.php.
// FIXME: password visible in ps list. How retarded.

$cmd = sprintf("mysqldump --user=%s --password=%s --host=%s %s > %s",
        DB_USER, DB_PASS, DB_HOST, IA_DB_TEMP_NAME, IA_ROOT . "db.sql");
log_print("Running '$cmd'");
system($cmd);

?>
