#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");

if (read_bool("Rebuild dep-check.db?", false)) {
    system(IA_ROOT . "scripts/dep-rebuild");
}

// read dependencies db
$exports = array();
$dep_buffer = file_get_contents(IA_ROOT."scripts/dep-check.db");
foreach (preg_split("/[\n\r]+/", $dep_buffer, -1, PREG_SPLIT_NO_EMPTY) as $line) {
    if (!($line = trim($line))) {
        continue;
    }

    list($ident, $fname) = split("\t", $line);

    if (!isset($exports[$fname])) {
        $exports[$fname] = array();
    }

    $exports[$fname][] = $ident;
}

//log_print_r($exports);

// some modules are bound to be included anywhere so we skip them for checking
unset($exports['config.php']);
unset($exports['common/common.php']);
unset($exports['common/log.php']);
unset($exports['common/security.php']);
unset($exports['www/config.php']);
unset($exports['www/utilities.php']);
unset($exports['www/url.php']);
unset($exports['www/index.php']);
unset($exports['www/identity.php']);
unset($exports['www/views/utilities.php']);
unset($exports['eval/utilities.php']);
unset($exports['eval/config.php']);
unset($exports['scripts/utilities.php']);

// some hacks
$exports['common/db/db.php'] = $exports['common/db/db.php']
                               + $exports['common/db/db_mysql.php'];
unset($exports['common/db/db_mysql.php']);

// grep for all identifiers
// this will take forever
foreach ($exports as $module => $idents) {
    // log_print_r("Processing $module");
    foreach ($idents as $ident) {
        // do grep
        $fd = popen(IA_ROOT."scripts/_dcgrep {$ident} {$module} ".IA_ROOT, "r");
        log_assert($fd);
        $buffer = fread($fd, 500*1024);
        pclose($fd);

        // print
        if ($buffer) {
            log_print("(possible) error calling {$ident} ({$module}) from these files:\n"
                      .$buffer);
        }
    }
}

?>
