#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");
db_connect();

// Configure the forum.
// SMF keeps paths in the database, we have to update them.
$ia_root = IA_ROOT;
$ia_url = IA_URL;

$query = sprintf("UPDATE ia_smf_themes ".
        "SET `value` = '%s' WHERE `variable` = 'theme_dir'",
        db_escape(IA_ROOT . "smf/Themes/infoarena2"));
db_query($query);
$query = sprintf("UPDATE ia_smf_themes ".
        "SET `value` = '%s' WHERE `variable` = 'theme_url'",
        db_escape(IA_URL . "forum/Themes/infoarena2"));
db_query($query);
$query = sprintf("UPDATE ia_smf_themes ".
        "SET `value` = '%s' WHERE `variable` = 'images_url'",
        db_escape(IA_URL . "forum/Themes/infoarena2/images"));
db_query($query);

?>
