#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT . "common/task.php");

// Attach a file(from the disk) to a certain page as attachment $attname.
function magic_file_attach($page, $attname, $file)
{
    if (!file_exists($file)) {
        log_error("File to attach not found ($file)");
    }
    if (!is_readable($file)) {
        log_error("File to attach not readable ($file)");
    }

    $mime = get_mime_type($file);
    $att = attachment_get($attname, $page);
    if ($att) {
        $id = $att['id'];
        attachment_update($id, $attname, filesize($file), $mime, $page, 0);
        log_print("Updating attachment $attname to $page mime type $mime.");
    } else {
        $id = attachment_insert($attname, filesize($file), $mime, $page, 0);
        log_print("New attachment $attname to $page mime type $mime.");
        $att = attachment_get($attname, $page);
    }
    if (!copy($file, attachment_get_filepath($att))) {
        log_error("Failed to copy file to attachment dir.");
    }
}

function magic_title($ugly_title) {
    $ugly_title = preg_replace("/ +/", "_", $ugly_title);
    $ugly_title = preg_replace("/\-+/", "_", $ugly_title);
    $ugly_title = preg_replace("/_+/", "_", $ugly_title);
    $ugly_title = strip_tags($ugly_title);
    return preg_replace("/([^a-z0-9_\-]*)/i", "", $ugly_title);
}

// Ask infoarena 1.0 path.
if (1 < $argc) {
    $ia1_path = $argv[1];
} else {
    $ia1_path = read_line("Where is infoarena1?");
}

//
// Connect to database.
//
log_assert(!isset($dbOldLink));
$dbOldLink = mysql_connect(DB_HOST, DB_USER, DB_PASS, true) or log_error('IMPORT: Cannot connect to database.');
mysql_select_db("infoarena1", $dbOldLink) or log_error('IMPORT: Cannot select database.');

if (read_bool("Delete wiki?", false)) {
    db_query("TRUNCATE TABLE ia_textblock_revision");
    db_query("DELETE FROM ia_textblock
                WHERE NOT (`name` LIKE 'template/%') AND
                      NOT (`name` LIKE 'sandbox/%') AND `name` != 'Home'");
}

if (read_bool("Delete attachments?", false)) {
    log_warn("Actual files are not deleted.");
    db_query("TRUNCATE TABLE ia_file");
}

//
// Import users.
//
if (read_bool("Import users?", false)) {
    $query = "SELECT * FROM devnet_users";

    $import_avatars = read_bool("Attach old avatars?", false);

    db_query("TRUNCATE TABLE ia_user");
    $result = mysql_query("SELECT * FROM devnet_users", $dbOldLink);
    if (!$result) {
        log_error('IMPORT: MYSQL error -> '.mysql_error($dbOldLink));
    }

    while ($row = mysql_fetch_assoc($result)) {
        // fill the user data
        $data = array();
        $data['username'] = $row['id'];
        $data['password'] = $row['password'];
        $data['email'] = $row['email'];
        $data['full_name'] = $row['name'];
        $data['newsletter'] = $row['receiveNewsletter'];
        if ($row['admin']) {
            $data['security_level'] = "admin";
        } else {
            $data['security_level'] = "normal";
        }

        // run query
        $res = user_create($data);
        if (!$res) {
            log_error("Failed creating user $data[username]");
        }

        if ($import_avatars) {
            $avatar_file = sprintf($ia1_path . 'www/infoarena/gfx/faces/%02d.gif', (int)$row['avatar']);
            magic_file_attach("user/" . $data['username'], "avatar", $avatar_file);
        }
    }
}

if (read_bool("Clean user password & email?", false)) {
    db_query("UPDATE `ia_user` SET `password`=SHA1(CONCAT(LCASE(`username`),`username`)), `email`='no@spam.com'");
}

//
// Import users into forum
//
if (read_bool("Import infoarena users into SMF user table?", false)) {
    log_print("Creating SMF users ...");
    $smfprefix = DB_SMF_PREFIX;

    // fetch all infoarena users
    $ia_users = db_fetch_all("SELECT * FROM ia_user");

    // count existing SMF users
    $smf_initial_count = db_query_value("SELECT COUNT(*) FROM {$smfprefix}members");

    // create/update smf users
    $cnt_create = $cnt_update = $cnt_delete = 0;
    foreach ($ia_users as $ia_user) {
        // see if SMF user already exists
        $query = sprintf("SELECT COUNT(*) FROM {$smfprefix}members
                          WHERE memberName = '%s'", db_escape($ia_user['username']));

        if (db_query_value($query)) {
            // user already exists => update info
            $cnt_update += smf_update_user($ia_user);
        }
        else {
            // new SMF user
            $member_id = smf_create_user($ia_user);
            log_assert($member_id, "Could not create SMF user for {$ia_user['username']}!");
            $cnt_create++;
        }
    }

    // Mark SMF users which have no infoarena counterpart.
    // These users will later be deleted via the SMF admin control panel
    // which takes care of all cascading deletes.
    $query = "
        UPDATE {$smfprefix}members AS su
        LEFT JOIN ia_user AS iu ON iu.username = su.memberName
        SET su.memberName = CONCAT('_deleteme_', su.memberName)
        WHERE iu.username IS NULL";
    db_query($query);

    // count users marked for deletion
    $query = "
        SELECT COUNT(*) FROM {$smfprefix}members
        WHERE memberName LIKE '_deleteme_%'
    ";
    $cnt_delete = db_query_value($query);

    log_print("DONE: imported {$cnt_update} "
              ."(".((int)(100*$cnt_update)/$smf_initial_count)."%), "
              ."created {$cnt_create}, {$cnt_delete} marked "
              ."for deletion");
}

//
//  Import rounds.
//
if (read_bool("Import rounds?", false)) {
    log_print("Importing rounds...");
    db_query("TRUNCATE TABLE ia_round");
    db_query("TRUNCATE TABLE ia_round_task");
    db_query("DELETE FROM ia_parameter_value WHERE `object_type` = 'round'");

    // DB query.
    $result = mysql_query("SELECT * FROM contests", $dbOldLink);
    if (!$result) {
        log_error('IMPORT: MYSQL error -> '.mysql_error($dbOldLink));
    }
    while ($contest = mysql_fetch_assoc($result)) {
        $contest['ID'] = strip_tags($contest['ID']);
        log_print("Adding round \"".$contest['ID']."\" ...");

        // Create round.
        $round = array(
                'id' => $contest['ID'],
                'type' => 'classic',
                'user_id' => 0,
                'hidden' => false,
                'title' => strip_tags($contest['name']),
                'page_name' => 'concursuri',
        );
        round_create($round);

        // Import task list.
        $task_list = mysql_query("SELECT * FROM tasktable_".$contest['ID']);
        $tasks = array();
        while ($task = mysql_fetch_assoc($task_list)) {
            $tasks[] = $task['ID'];
        }    
        round_update_task_list($round['id'], $tasks);

        log_print("DONE ".$round['id']."\n");
    }
}

//
//  Import scores
//
if (read_bool("Import scores?", false)) {
    log_print("Importing scores... might take a while.");

    // Prevents adding missing contests
    // FIXME: user.
    db_query("TRUNCATE TABLE ia_score");
    $query = "
            SELECT * FROM `scores`
            JOIN contests on contests.ID = contestID";
    $score_list = mysql_query($query, $dbOldLink);
    if (!$score_list) {
        log_error('IMPORT: MYSQL error -> '.mysql_error($dbOldLink));
    }
    while ($score = mysql_fetch_assoc($score_list)) {
        $rid = $score['contestID'];
        $tid = $score['taskID'];
        // FIXME: USERS.
        $user = user_get_by_username($score['userID']);
        $uid = $user['id'];

        score_update("score", $uid, $tid, $rid, $score['score']);
        score_update("submit-count", $uid, $tid, $rid, $score['score']);
    }
}

//
//  Import tasks
//
if (read_bool("Import tasks?", false)) {
    db_query("TRUNCATE TABLE ia_task");
    db_query("DELETE FROM ia_parameter_value WHERE `object_type` = 'task'");
    $import_eval = read_bool("Import task evaluators?", true);
    $import_tests = read_bool("Import task tests?", true);

    $task_list = mysql_query("SELECT * FROM tasktable_arhiva", $dbOldLink);
    if (!$task_list) {
        log_error('IMPORT: MYSQL error -> '.mysql_error($dbOldLink));
    }

    while ($oldtask = mysql_fetch_assoc($task_list)) {
        log_print("Adding task \"".$oldtask['ID']."\" ...");

        // Basic shit.
        $task = array(
                'id' => $oldtask['ID'],
                'title' => $oldtask['name'],
                'type' => 'classic',
                'hidden' => 'false',
                'author' => $oldtask['autor'],
                'source' => "info-arena 1.0",
                'user_id' => 0,
                'page_name' => TB_TASK_PREFIX . $oldtask['ID']
        );
        task_create($task);
    
        $parameters = array();

        $parameters['tests'] = $oldtask['evalsteps'];
        $parameters['timelimit'] = $oldtask['timelimit'];
        $parameters['memlimit'] = 65536;
        $parameters['unique_output'] = '0';
        $parameters['evaluator'] = "not_working.c";
 
        // Handle evaluator.
        if ($import_eval) {
            $task_dir = $ia1_path . "eval/arhiva/$task_id/";
            if (file_exists($task_dir . "eval.c")) {
                $parameters['evaluator'] = "eval.c";
                log_print("Found C evaluator.");
            } else if (file_exists($task_dir . "eval.cpp")) {
                $parameters['evaluator'] = "eval.cpp";
                log_print("Found C++ evaluator.");
            } else if (file_exists($task_dir . "eval.pas")) {
                $parameters['evaluator'] = "eval.pas";
                log_print("Found Pascal evaluator.");
            } else {
                log_warn("No evaluator found, assuming unique output");
                $parameters['evaluator'] = "";
                $parameters['unique_output'] = "1";
            }
        }

        if ($import_eval && $parameters['evaluator']) {
            magic_file_attach(
                    $task['page_name'],
                    "grader_" . $parameters['evaluator'],
                    $task_dir . $parameters['evaluator']);
        }

        // Tests. Yay. HACK: Also determines okfiles.
        $parameters['okfiles'] = '1';
        if ($import_tests) {
            for ($tid = 1; $tid <= $oldtask['evalsteps']; ++$tid) {
                // Attach input.
                magic_file_attach($task['page_name'], "grader_test$tid.in", $task_dir . "test$tid.in");

                // Attach ok file.
                if (!file_exists($task_dir . "test$tid.ok")) {
                    $parameters['okfiles'] = '0';
                    log_warn("TASK $task_id HAS NO OK FILES");
                } else {
                    magic_file_attach($task['page_name'], "grader_test$tid.ok", $task_dir . "test$tid.ok");
                }
            }
        }

        // Update parameters.
        $errs = task_validate_parameters('classic', $parameters);
        if ($errs) {
            log_print_r($errs);
            log_print_r($parameters);
            log_error("Task parameters didn't validate");
        }
        task_update_parameters($task['id'], $parameters);  
        log_print("DONE ".$task['id']."\n");
    }
}

?>
