#! /usr/bin/env php
<?php

require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT . "common/db/textblock.php");

$page_list = textblock_get_by_prefix('stiri/', true, false);

if (count($page_list) == 0) {
    log_error("No pages found.");
}

if (!read_bool("Are you sure you want to move ".count($page_list)." pages?", false)) {
    log_print("Aborted");
    die();
}

foreach ($page_list as $page) {
    $old_page = textblock_get_revision($page['name'], 1);
    textblock_delete($page['name']);
    textblock_add_revision(
            $page['name'], $page['title'], $page['text'],
            $page['user_id'], 'protected', $old_page['timestamp']);
}

?>
