#! /usr/bin/env php
<?php

// recomputes ratings *FROM SCRATCH*
// (deletes existing ratings)
//
// FIXME: It now relies on the `update-ratings` tool. This isn't
// very efficient since `update-ratings` always starts from scratch.

require_once(dirname($argv[0]) . "/utilities.php");
require_once(IA_ROOT."common/db/score.php");

// first, delete all ratings
// FIXME: Turn this into db API call
log_print("Deleting all current ratings");
db_query("DELETE FROM ia_score WHERE `name` IN ('rating', 'deviation')");
db_query("UPDATE ia_user SET rating_cache = NULL");

$rounds = rating_rounds();

log_print("Recomputing ratings for ".count($rounds)." rounds...");
$i = 1;
$cnt = count($rounds);
foreach ($rounds as $round_id => $round) {
    echo "\n\n\nRound {$i}/{$cnt}\n";
    system("./update-ratings {$round_id}");
    $i++;
}

?>
