/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class infoarena_InfoarenaJudge */

#ifndef _Included_infoarena_InfoarenaJudge
#define _Included_infoarena_InfoarenaJudge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     infoarena_InfoarenaJudge
 * Method:    setLimits
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_infoarena_InfoarenaJudge_setLimits
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
